# This is a basic workflow to help you get started with Actions on CMSIS projects
# See also https://community.arm.com/developer/tools-software/tools/b/tools-software-ides-blog/posts/infrastructure-for-continuous-integration-tests

name: Arm Virtual Hardware example - github hosted - remote AWS via avhclient

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
# To allow you to run this workflow manually
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
  AWS_IAM_PROFILE: ${{ secrets.AWS_IAM_PROFILE }}
  AWS_SECURITY_GROUP_ID: ${{ secrets.AWS_SECURITY_GROUP_ID }}
  AWS_SUBNET_ID: ${{ secrets.AWS_SUBNET_ID }}


jobs:
  arm_virtual_hardware:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install AVH Client for Python
        run: |
          pip install git+https://github.com/ARM-software/avhclient.git@v0.1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::720528183931:role/Proj-vht-assume-role
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - name: Execute test suite on Arm Virtual Hardware at AWS
        run: |
          avhclient -b aws execute --specfile ./avh.yml
      - name: Fetch results from Arm Virtual Hardware
        run: |
           cat ./Platform_FVP_Corstone_SSE-300_Ethos-U55/microspeech.Reference.log
           cat ./Platform_FVP_Corstone_SSE-300_Ethos-U55/microspeech.SIMD.log
           cat ./Platform_FVP_Corstone_SSE-300_Ethos-U55/microspeech.Helium.log
      - name: Decode EventRecorder logs
        run: |
           wget https://github.com/ARM-software/CMSIS-View/releases/download/tools%2Feventlist%2F1.0.10/eventlist-linux64.tar.gz
           tar -xvf eventlist-linux64.tar.gz 
           chmod +x eventlist-linux64/eventlist
           eventlist-linux64/eventlist -s ./Platform_FVP_Corstone_SSE-300_Ethos-U55/microspeech.Reference.EventRecorder.log 
           eventlist-linux64/eventlist -s ./Platform_FVP_Corstone_SSE-300_Ethos-U55/microspeech.SIMD.EventRecorder.log 
           eventlist-linux64/eventlist -s ./Platform_FVP_Corstone_SSE-300_Ethos-U55/microspeech.Helium.EventRecorder.log 
          